- name: Firewalld rules
  hosts: webservers
  become: yes
  tasks:
    - name: Add rule for port 80/tcp
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes
        