- name: "Update All VMs"
  hosts: all
  become: yes
  tasks:
  - name: "Update Debian based VMs"
    apt:
      update_cache: yes
    when: ansible_facts['os_family'] == "Debian"
  
  - name: "Upgrade Debian based VMs"
    apt:
      upgrade: dist
    when: ansible_facts['os_family'] == "Debian"

  - name: "Update and Upgrade RedHat based VMs"
    yum:
      name: '*'
      state: latest
    when: ansible_facts['os_family'] == "RedHat"

- name: Install and start webserver 
  hosts: webservers
  become: yes
  tasks:
    - name: Install httpd webserver
      ansible.builtin.yum:
        name: httpd
        state: present
    
    - name: Start webserver
      ansible.builtin.service:
        name: httpd
        state: started
